title: VirLaDEE Book
description: VirLaDEE Book
theme: just-the-docs

url: https://virladee.github.io/website

aux_links:
  VirLaDEE site: https://www.sdu.dk/en/forskning/technologyentrepreneurshipandinnovation/researchprojects/virladee
  
plugins: 
    - jekyll-default-layout

logo: "/images/Virladee_logo.png"

heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light
