title:  VirLaDEE Book
description: > # VirLaDEE Book.
baseurl: "/website" # the subpath of your site, e.g. /blog/
url: "https://virladee.github.io" # the base hostname & protocol for your site



# Build settings
markdown: kramdown

# theme: jekyll-theme-tactile
