title: VirLaDEE Book
description: VirLaDEE Book
theme: just-the-docs

url: https://virladee.github.io/website

aux_links:
  VirLaDEE site: https://www.sdu.dk/en/forskning/technologyentrepreneurshipandinnovation/researchprojects/virladee
  
plugins: 
    - jekyll-default-layout
    - jekyll-toc
    
logo: "/images/Virladee_logo.png"

heading_anchors: true

# Color scheme supports "light" (default) and "dark"
color_scheme: light


# TOC Settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist
